### ISSUE TITLE
integrate with 3rd part to register user

### ISSUE THREAD

**Issue by lsmialowski** [asia-smialowski/sporty#6]
as a annonymous I want to register new account

**Comment by asia-smialowski** [comment]
Done:
changed project structure
integrated with auth0 library to sign in, log in and log out - created project in Auth0 account, set envs, use auth0 to login process
created navigation bar with buttons to log in, log out , sign in and tabs
created json server

**Comment by asia-smialowski** [comment]
https://github.com/asia-smialowski/sporty/pull/11
